name: 'SafeChat-Downloader'
main: 'studio.thevipershow.safechatdownloader.SafeChatDownloader'
version: ${project.version}
description: 'Official plugin to download and run SafeChat'
author: 'TheViperShow'
api-version: '1.13'
load: STARTUP
